config/routes.rb
Rails.application.routes.draw do
  root to: 'application#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  get '/about' => 'application#about'
  get '/tasks/:id/priority' => 'tasks#edit_priority', as: 'edit_task_priority'
  get '/tasks/:id/description' => 'tasks#edit_description', as: 'edit_task_description'
  get '/admin' => 'admin#home'
  get '/admin/search' => 'admin#search', as: 'search'
  post '/login_as/:id' => 'admin#log_in_as', as: 'login_as'
  resources :users, only: [:new, :create, :update, :show]
  resources :lists, only: [:create, :destroy]
  resources :tasks, only: [:create, :destroy, :update]
  resources :stars, only: [:create, :destroy]
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_one :star, :as => :starable, dependent: :destroy
  validates_presence_of :name, :user_id
  acts_as_paranoid

  def sort_tasks_by_priority
    order = ['low', 'medium', 'high']
    tasks.sort { |a, b| order.index(b.priority) <=> order.index(a.priority) }
  end

  def self.search_all_like(keyword)
    with_deleted.where("name LIKE ?", "%#{keyword}%")
  end

  def self.search_active_like(keyword)
    where("name LIKE ?", "%#{keyword}%")
  end

  def self.active_with_most_tasks
    List.joins(:tasks).select("lists.*, COUNT(tasks.*) AS num_tasks").group(:id).order("num_tasks DESC").limit(1).first
  end

  def self.average_tasks_per_list
    num_tasks = Task.with_deleted.length
    num_lists = List.with_deleted.length
    num_lists / num_tasks
  end

  def self.most_common_name
    List.with_deleted.group(:name).order('count_id DESC').limit(1).count(:id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def create
    @list = List.new(list_params)
    if @list.save
      list_partial = render_to_string(partial: 'lists/list', locals: {list: @list})
      dropdown_option = render_to_string(partial: 'lists/dropdown_option', locals: {list: @list})
      render json: {list: @list, list_partial: list_partial, options_partial: dropdown_option}
    else
      flash[:danger] = "Your list needs a name!"
      flash_partial = render_to_string(partial: 'shared/flash', locals: { flash: flash } )
      render json: { flash_partial: flash_partial }
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list_id = @list.id
    @list.destroy
    render json: {list_id: @list_id}
  end

  private

    def list_params
      params.require(:list).permit(:name, :user_id)
    end
end

app/views/lists/_add_list.html.erb
<%= form_for @list, html: {class: "form-horizontal", id: "add-list"} do |f| %>
  <%= f.submit 'Add List', class: "btn btn-primary" %>
  <%= f.hidden_field :user_id, value: @user.id %>
  <%= f.text_field :name, placeholder: "List Name" %>
<% end %>

app/views/lists/_dropdown_option.html.erb
<option value="<%= list.id %>"><%= list.name %></option>

app/views/lists/_list.html.erb
<div class="col-lg-4 list" id="whole-list-<%= list.id %>">
  <div class="list-group">
    <div class="list-group-item" id="list-<%= list.id %>">
      <div class="row">
        <div class="col-xs-1">
          <span class="star-span list-star btn-group">
            <% if list.star.nil? %>
              <%= render partial: 'stars/star', locals: {starable: list} %>
            <% else %>
              <%= render partial: 'stars/unstar', locals: {star: list.star} %>
            <% end %>
          </span>
        </div>
        <div class="col-xs-9">
          <h2 class="list-group-item-heading"><%= list.name %></h4>
        </div>
        <div class="col-xs-1">
          <%= button_to "X", list_path(list), method: :delete, class: "btn btn-primary btn-xs", form_class: "delete-list" %>
        </div>
      </div>
    </div>
    <ul class="list-group">
      <% list.tasks.each do |task| %>
        <%= render partial: "tasks/task", locals: {task: task} %>
      <% end %>
    </ul>
  </div>
</div>