config/routes.rb
Rails.application.routes.draw do
  root to: 'application#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  get '/about' => 'application#about'
  get '/tasks/:id/priority' => 'tasks#edit_priority', as: 'edit_task_priority'
  get '/tasks/:id/description' => 'tasks#edit_description', as: 'edit_task_description'
  get '/admin' => 'admin#home'
  get '/admin/search' => 'admin#search', as: 'search'
  post '/login_as/:id' => 'admin#log_in_as', as: 'login_as'
  resources :users, only: [:new, :create, :update, :show]
  resources :lists, only: [:create, :destroy]
  resources :tasks, only: [:create, :destroy, :update]
  resources :stars, only: [:create, :destroy]
end

app/views/admin/_active.html.erb
<table class="table table-striped table-hover">
  <legend>Active Items</legend>
  <thead>
    <th>Lists</th>
    <th>Tasks</th>
    <th>Starred Lists</th>
    <th>Starred Tasks</th>
  </thead>
  <tbody>
    <tr>
      <td><%= List.all.length %></td>
      <td><%= Task.all.length %></td>
      <td><%= Star.active_starred_lists %></td>
      <td><%= Star.active_starred_tasks %></td>
    </tr>
  </tbody>
</table>

app/views/admin/_list_results.html.erb
<legend>List Results</legend>
<table class="table table-striped table-hover list-table">
  <thead>
    <tr>
      <th colspan="3">
        <label class="select-label">Filter by user: <select id="list-filter">
          <option value="all" selected>all</option>
          <% User.non_admin.each do |user| %>
            <option value="<%= user.username %>"><%= user.username %></option>
          <% end %>
        </select></label>
        <label> Include deleted: <input type="checkbox" class="deleted list" value="true"></label>
      </th>
    </tr>
    <tr>
      <th>List</th>
      <th>User</th>
      <th class="right-align">Deleted</th>
    </tr>
  </thead>
  <tbody>
    <% lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= list.user.username %></td>
        <td class="right-align">
          <% unless list.deleted_at.nil? %>
            ☓
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/_list_stats.html.erb
<legend>List Statistics</legend>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Active with most tasks</th>
      <th>User</th>
      <th># Tasks</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @list_stats[:active][:most_tasks].name %></td>
      <td><%= @list_stats[:active][:most_tasks].user.username %></td>
      <td><%= @list_stats[:active][:most_tasks].tasks.length %></td>
    </tr>
    <tr>
      <th colspan="2">Avg # tasks per list including deleted</th>
      <th><%= @list_stats[:all][:avg_tasks_per_list] %></th>
    </tr>
  </tbody>
  <thead>
    <tr>
      <th colspan="3">Most common list name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="2"><%= @list_stats[:all][:most_common_name][:name] %></td>
      <td><%= @list_stats[:all][:most_common_name][:count] %> times</td>
    </tr>
  </tbody>
</table>

app/views/admin/_search.html.erb
<legend>Search Lists and Tasks by name/description</legend>
<form class="search-form" method="get" action="/admin/search">
  <input type="text" name="keyword">
  <input type="submit" name="commit" value="Search" class="btn btn-primary">
  <div class="form-group">
    <label><input type="checkbox" class="search-option" name="include[task]" value="true"> Tasks</label><br>
    <label><input type="checkbox" class="search-option" name="include[list]" value="true"> Lists</label><br>
  </div>
</form>

app/views/admin/_task_results.html.erb
<legend>Task Results</legend>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th colspan="3">
        <label class="select-label">Filter by priority: <select id="task-filter">
          <option value="all" selected>all</option>
          <option value="low">low</option>
          <option value="medium">medium</option>
          <option value="high">high</option>
        </select></label>
        <label> Include deleted: <input type="checkbox" class="deleted task" value="true"></label>
      </th>
    </tr>
    <tr>
      <th>Task</th>
      <th>Priority</th>
      <th class="right-align">Deleted</th>
    </tr>
  </thead>
  <tbody class="task-table">
    <% tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td class="right-align">
          <% unless task.deleted_at.nil? %>
            ☓
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/_task_stats.html.erb
<legend># Tasks by priority</legend>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Active</th>
    </tr>
    <tr>
      <th>Low</th>
      <th>Medium</th>
      <th>High</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @task_stats[:active][:low] %></td>
      <td><%= @task_stats[:active][:medium] %></td>
      <td><%= @task_stats[:active][:high] %></td>
    </tr>
  </tbody>
  <thead>
    <tr>
      <th>Total</th>
    </tr>
    <tr>
      <th>Low</th>
      <th>Medium</th>
      <th>High</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @task_stats[:all][:low] %></td>
      <td><%= @task_stats[:all][:medium] %></td>
      <td><%= @task_stats[:all][:high] %></td>
    </tr>
  </tbody>
</table>

app/views/admin/_totals.html.erb
<table class="table table-striped table-hover">
  <legend>Total created</legend>
  <thead>
    <th>Lists</th>
    <th>Tasks</th>
    <th>Stars</th>
  </thead>
  <tbody>
    <tr>
      <td><%= List.with_deleted.length %></td>
      <td><%= Task.with_deleted.length %></td>
      <td><%= Star.with_deleted.length %></td>
    </tr>
  </tbody>
</table>

app/views/admin/_user_stats.html.erb
<legend>User Statstics</legend>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Most active lists</th>
      <th># Lists</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user_with[:most_active_lists].username %></td>
      <td><%= @user_with[:most_active_lists].lists.length %></td>
    </tr>
  </tbody>
  <thead>
    <tr>
      <th>Most total lists</th>
      <th># Lists</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user_with[:most_total_lists].username %></td>
      <td><%= @user_with[:most_total_lists].lists.with_deleted.length %></td>
    </tr>
  </tbody>
  <thead>
    <tr>
      <th>Most active tasks</th>
      <th># Tasks</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user_with[:most_active_tasks].username %></td>
      <td><%= @user_with[:most_active_tasks].tasks.length %></td>
    </tr>
  </tbody>
</table>

app/views/admin/_users.html.erb
<table class="table table-striped table-hover">
  <legend>Users</legend>
  <thead>
    <th>Username</th>
    <th>Lists Created</th>
    <th>Tasks Created</th>
    <th>Items Starred</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username %></td>
        <td><%= user.lists_total %></td>
        <td><%= user.tasks_total %></td>
        <td><%= user.total_starred_items %></td>
        <td><%= link_to 'Log In', login_as_path(id: user.id), class: 'btn btn-primary btn-xs', method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/home.html.erb
<%= javascript_include_tag 'admin.js' %>

<div class="row well">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="center-header">Welcome, Supreme Leader!</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <%= render 'users' %>
    </div>
    <div class="col-xs-4">
      <div class="col-xs-12">
        <%= render 'totals' %>
      </div>
      <div class="col-xs-12">
        <%= render 'active' %>
      </div>
      <div class="col-xs-12">
        <%= render 'task_stats' %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="col-xs-12">
        <%= render 'user_stats' %>
      </div>
      <div class="col-xs-12">
        <%= render 'list_stats' %>
      </div>
    </div>
  </div>
  <div class="row results">
    <div class="col-xs-4">
      <%= render 'search' %>
    </div>
    <div class="col-xs-4 list-results">

    </div>
    <div class="col-xs-4 task-results">

    </div>
  </div>
</div>