config/routes.rb
Rails.application.routes.draw do
  root to: 'application#home'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  get '/about' => 'application#about'
  get '/tasks/:id/priority' => 'tasks#edit_priority', as: 'edit_task_priority'
  get '/tasks/:id/description' => 'tasks#edit_description', as: 'edit_task_description'
  get '/admin' => 'admin#home'
  get '/admin/search' => 'admin#search', as: 'search'
  post '/login_as/:id' => 'admin#log_in_as', as: 'login_as'
  resources :users, only: [:new, :create, :update, :show]
  resources :lists, only: [:create, :destroy]
  resources :tasks, only: [:create, :destroy, :update]
  resources :stars, only: [:create, :destroy]
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">List-A-Task</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <% if admin_masquerade? %>
            <li><%= link_to current_user.username, user_path(current_user) %></li>
          <% end %>
          <% if admin? || admin_masquerade? %>
            <li><%= link_to 'Admin Panel', admin_path %></li>
          <% else %>
            <li><%= link_to current_user.username, user_path(current_user) %></li>
          <% end %>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        <% else %>
          <li><a href="/login">Log In</a></li>
          <li><a href="/signup">Sign Up</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskLister</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/nav' %>
  <div class="container top-margin">
    <div class="row" id="flash">
      <%= render 'shared/flash' %>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<div class="row">
  <div class="col-xs-6">
    <%= render 'shared/about' %>
  </div>
</div>